### ISSUE TITLE
Adding scales functions for easy LaCroix-ing?

### ISSUE THREAD

**Issue by monicathieu** [johannesbjork/LaCroixColoR#5]
hi folks,

I've typically been calling LaCroix palettes for ggplots using the following general syntax:

``` r
ggplot(mtcars, aes(x = wt, y = mpg, color = factor(cyl))) +
  geom_point() +
  scale_color_manual(values = lacroix_palette("PassionFruit", n = 3, type = "discrete"))
```

I realized that `lacroix_palette()` plays well enough with `ggplot2`'s `discrete_scale()` and `scale_color_gradientn()` that one could write wrapper functions to apply a LaCroix palette to any graph without needing to explicitly specify the `n` argument, so `ggplot2` will flexibly set `n` to be the appropriate number of colors. Like the following:

``` r
# Discrete:
ggplot(mtcars, aes(x = wt, y = mpg, color = factor(cyl))) +
  geom_point() +
  scale_color_lacroix("PassionFruit", discrete = TRUE)

# Or continuous:
ggplot(mtcars, aes(x = wt, y = mpg, color = hp)) +
  geom_point() +
  scale_color_lacroix("PassionFruit", discrete = FALSE)
```

I have some code I've written that should work--if you're interested, I'll submit a pull request so you can check it out!

**Comment by johannesbjork** [comment]
Hi there! Yeah, please do--this is cool! 👍
